name: dyva-worldlm
channels:
  - conda-forge
  - bioconda
  - pytorch
  - pytorch-lts
  - deepmodeling
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2025.6.15
  - ld_impl_linux-64=2.44
  - libffi=3.4.6
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgomp=15.1.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnsl=2.0.1
  - libsqlite=3.50.2
  - libuuid=2.38.1
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.5.1
  - pip=25.1.1
  - python=3.11.0
  - readline=8.2
  - tk=8.6.13
  - wheel=0.45.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - pip:
      - absl-py==2.3.1
      - accelerate==1.8.1
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyio==4.11.0
      - attrs==25.3.0
      - beautifulsoup4==4.13.4
      - brotli==1.1.0
      - certifi==2025.6.15
      - charset-normalizer==3.4.2
      - click==8.2.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - datasets==3.0.2
      - decord==0.6.0
      - diffusers==0.34.0
      - dill==0.3.8
      - draccus==0.11.1
      - einops==0.8.1
      - fastapi==0.118.0
      - ffmpy==0.6.1
      - filelock==3.18.0
      # - flash-attn==2.8.0.post2
      - fonttools==4.58.5
      - frozenlist==1.7.0
      - fsspec==2024.9.0
      - gdown==5.2.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - gradio==5.47.2
      - gradio-client==1.13.3
      - groovy==0.1.2
      - grpcio==1.74.0
      - h11==0.16.0
      - h5py==3.14.0
      - hf-xet==1.1.5
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.35.3
      - idna==3.10
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==8.7.0
      - jinja2==3.1.6
      - joblib==1.5.1
      - jsonlines==4.0.0
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - llava==1.2.2.post1
      - markdown==3.8.2
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.3
      - mdurl==0.1.2
      - mergedeep==1.3.4
      - mpmath==1.3.0
      - multidict==6.6.4
      - multiprocess==0.70.16
      - mypy-extensions==1.1.0
      - networkx==3.5
      - ninja==1.11.1.4
      - numpy==2.3.1
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-ml-py==12.575.51
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - nvitop==1.5.1
      - optimum==1.26.1
      - orjson==3.11.3
      - packaging==25.0
      - pandas==2.3.1
      - pillow==11.0.0
      - platformdirs==4.3.8
      - prismatic==0.0.2
      - propcache==0.3.2
      - protobuf==6.31.1
      - psutil==7.0.0
      - pyarrow==21.0.0
      - pycocotools==2.0.10
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pydub==0.25.1
      - pygments==2.19.2
      - pyparsing==3.2.3
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.2
      - pyyaml-include==1.4.1
      - regex==2024.11.6
      - requests==2.32.4
      - rich==14.0.0
      - ruff==0.13.2
      - safehttpx==0.1.6
      - safetensors==0.5.3
      - scikit-image==0.25.2
      - scikit-learn==1.7.0
      - scipy==1.16.0
      - sdata==0.0.1
      - semantic-version==2.10.0
      - sentencepiece==0.2.0
      - sentry-sdk==2.32.0
      - setuptools==80.9.0
      - sgm==0.1.0
      - shellingham==1.5.4
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.7
      - starlette==0.48.0
      - sympy==1.14.0
      - tenacity==9.1.2
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - tifffile==2025.6.11
      - timm==0.9.10
      - tokenizers==0.21.2
      - toml==0.10.2
      - tomlkit==0.13.3
      - torch==2.7.1
      - torchaudio==2.7.1
      - torchvision==0.22.1
      - tqdm==4.67.1
      - transformers==4.54.0.dev0
      - triton==3.3.1
      - typer==0.19.2
      - typing-extensions==4.14.1
      - typing-inspect==0.9.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - uvicorn==0.37.0
      - wandb==0.21.0
      - websockets==15.0.1
      - werkzeug==3.1.3
      - xxhash==3.5.0
      - yarl==1.20.1
      - zipp==3.23.0
